In [186]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import sklearn

In [187]:
data = pd.read_csv('newdata.csv')

data.value_counts()

team1  team2  team3  team4  team5  team6  winner
7028   2987   4536   4607   3102   3184   1         2
2052   5172   3026   3007   4207   3244   0         2
                     4607   3102   3184   0         2
                     2823   2508   3630   0         2
4198   5913   3751   2823   2508   3630   1         2
                                                   ..
2846   3184   3026   7028   4207   2513   0         1
2825   7038   5996   2987   2529   3102   1         1
       4664   4198   2530   4207   3202   1         1
       2513   3407   3055   5637   2470   1         1
7850   3871   4664   3026   2509   3038   1         1
Name: count, Length: 105, dtype: int64

In [188]:
target = data.pop("winner")

In [189]:
ratio = 0.75
 
total_rows = data.shape[0]
train_size = int(total_rows*ratio)

target_rows = data.shape[0]
target_train_size = int(target_rows*ratio)
# Split data into test and train
train = data[0:train_size]
test = data[train_size:]

targettrain = train = data[0:target_train_size]
test = data[target_train_size:]

In [190]:
print(train)
print(test)
print(target)

    team1  team2  team3  team4  team5  team6
0    2052   5172   3026   4607   3102   3184
1    2052   5172   3026   4607   3102   3184
2    2052   5172   3026   3007   4207   3244
3    2052   5172   3026   3007   4207   3244
4    4198   5913   3751   2823   2508   3630
..    ...    ...    ...    ...    ...    ...
78   5996   2498   2515   2500   3407   3202
79   2825   7038   5996   2987   2529   3102
80   2530   2500   2518   7180   2232   3038
81   3454   6709   3745   4198   4549   5913
82   3871   3751   2855   2501   2823   3055

[83 rows x 6 columns]
     team1  team2  team3  team4  team5  team6
83    3023   2879   2181   2498   4229   4664
84    2532   5232   2987   3026   3202   2529
85    7028   5172   2470   4536   3058   2500
86    3407   3244   6709   2509   2825   2846
87    5637   2508   4207   2480   3299   2823
88    3038   2501   3751   5541   3745   2502
89    4664   5541   4536   3244   3454   3102
90    4664   3102   3134   3630   2855   2232
91    5464   4198   785

In [191]:
data = np.array(data)
print(data)

[[2052 5172 3026 4607 3102 3184]
 [2052 5172 3026 4607 3102 3184]
 [2052 5172 3026 3007 4207 3244]
 [2052 5172 3026 3007 4207 3244]
 [4198 5913 3751 2823 2508 3630]
 [4198 5913 3751 2823 2508 3630]
 [4198 5913 3751 2823 2508 3630]
 [7028 2987 4536 2509 5232 2500]
 [7028 2987 4536 2509 5232 2500]
 [7028 2987 4536 2509 5232 2500]
 [4607 3102 3184 5464 2502 5434]
 [4607 3102 3184 2232 2502 5434]
 [7038 2052 5232 2855 3058 2513]
 [3184 3038 3023 2823 2987 5434]
 [2513 2509 2879 3751 2518 2532]
 [2515 2480 3007 3745 5232 2825]
 [3102 2846 2498 5913 5464 3058]
 [5996 5172 3298 4198 5541 2181]
 [4536 2530 4549 3299 4229 3407]
 [4207 3751 3630 4607 3244 3023]
 [2501 2855 7068 5637 2987 2500]
 [2470 7180 6709 5434 3134 3202]
 [7850 3871 4664 3026 2509 3038]
 [4229 4607 4198 2825 7028 2532]
 [2232 3184 7028 2052 3055 2508]
 [7038 2823 2529 2502 3454 2879]
 [3745 2515 5637 2987 2846 2530]
 [3630 2501 7180 4207 2181 3007]
 [2480 2470 3038 2498 4549 4607]
 [3751 7028 2052 7850 2825 5172]
 [3454 554

In [192]:
np.asarray(train)
np.asarray(targettrain)
targetflat = np.argmax(targettrain, axis=1)

In [193]:
model = LogisticRegression(multi_class='ovr', solver='liblinear', max_iter=1000)
model.fit(train, targetflat)


LogisticRegression(max_iter=1000, multi_class='ovr', solver='liblinear')

In [194]:
model.predict(np.array([[3023,2501,3871,5172,2052,3026]]))

/Users/64008733/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([3])

In [196]:
probabilities = model.predict_proba(train)
print(probabilities)

[[9.19476276e-12 9.90294347e-01 4.02883545e-03 5.67472133e-03
  9.44994528e-17 2.09595229e-06]
 [9.19476276e-12 9.90294347e-01 4.02883545e-03 5.67472133e-03
  9.44994528e-17 2.09595229e-06]
 [7.49870371e-10 9.96656715e-01 2.99306308e-03 7.64466820e-12
  2.20197054e-04 1.30024135e-04]
 [7.49870371e-10 9.96656715e-01 2.99306308e-03 7.64466820e-12
  2.20197054e-04 1.30024135e-04]
 [1.87883996e-02 9.78339659e-01 2.86119098e-03 5.63184384e-12
  2.84510811e-22 1.07508540e-05]
 [1.87883996e-02 9.78339659e-01 2.86119098e-03 5.63184384e-12
  2.84510811e-22 1.07508540e-05]
 [1.87883996e-02 9.78339659e-01 2.86119098e-03 5.63184384e-12
  2.84510811e-22 1.07508540e-05]
 [9.92106431e-01 1.29677054e-08 7.80170340e-03 2.37509545e-12
  9.17591266e-05 9.35406587e-08]
 [9.92106431e-01 1.29677054e-08 7.80170340e-03 2.37509545e-12
  9.17591266e-05 9.35406587e-08]
 [9.92106431e-01 1.29677054e-08 7.80170340e-03 2.37509545e-12
  9.17591266e-05 9.35406587e-08]
 [3.10971951e-07 3.30965751e-08 6.90150362e-03 9.8